acme_biomedical_homepage:
    pattern:  /
    defaults: { _controller: AcmeBiomedicalBundle:Default:index }
    requirements: 
      _method: GET
    
acme_biomedical_search:
    pattern:  /
    defaults: { _controller: AcmeBiomedicalBundle:Default:showConcepts }
    requirements: 
      _method: POST

acme_biomedical_search_ontology:
    pattern:  /search_ontology
    defaults: { _controller: AcmeBiomedicalBundle:Default:showOntologies }
    requirements: 
      _method: POST
      
acme_biomedical_ontology:
    pattern:  /search_ontology
    defaults: { _controller: AcmeBiomedicalBundle:Default:goToOntologie }
    requirements: 
      _method: GET
      
acme_biomedical_semantic_distance_two_concepts:
    pattern:  /semantic_distance
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:index }
    requirements: 
      _method: GET
      
acme_biomedical_semantic_distance_concept_dist:
    pattern:  /semantic_distance_concept
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:indexConcept }
    requirements: 
      _method: GET