acme_biomedical_homepage:
    pattern:  /
    defaults: { _controller: AcmeBiomedicalBundle:Default:index }
    requirements: 
      _method: GET

######################################################################################## 
#Patterns permettant l'auto-complétion
   
acme_biomedical_search:
    pattern:  /
    defaults: { _controller: AcmeBiomedicalBundle:Default:showConcepts }
    requirements: 
      _method: POST

acme_biomedical_search_ontology:
    pattern:  /search_ontology
    defaults: { _controller: AcmeBiomedicalBundle:Default:showOntologies }
    requirements: 
      _method: POST
      
acme_biomedical_search_ontology_with_term:
    pattern: /search_ontology_term
    defaults: { _controller: AcmeBiomedicalBundle:Default:showOntologiesWithConcept }
    requirements: 
      _method: POST

acme_biomedical_search_term_with_ontology:
    pattern: /search_term_ontology
    defaults: { _controller: AcmeBiomedicalBundle:Default:showConceptsWithOntology }
    requirements: 
      _method: POST
      
########################################################################################  
acme_biomedical_language:
    pattern: /choose_language/{langue}
    defaults: { _controller: AcmeBiomedicalBundle:Default:changeLanguage }

acme_biomedical_search_term:
    pattern: /search
    defaults: { _controller: AcmeBiomedicalBundle:Default:goToTerm }
    requirements:
      _method: GET
                
acme_biomedical_ontology:
    pattern:  /search_ontology
    defaults: { _controller: AcmeBiomedicalBundle:Default:goToOntologie }
    requirements: 
      _method: GET
      
acme_biomedical_semantic_distance_two_concepts:
    pattern:  /semantic_distance
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:index }
    requirements: 
      _method: GET
      
acme_biomedical_semantic_distance_concept_dist:
    pattern:  /semantic_distance_concept
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:indexConcept }
    requirements: 
      _method: GET
      
acme_biomedical_sdtc:
    pattern:  /search_semantic_distance
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:searchCalculateDistance }
    requirements: 
      _method: POST
      
acme_biomedical_all_concepts_in_distance:
    pattern:  /concepts_in_distance
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:searchConceptsInDistance }
    requirements: 
      _method: POST
      
acme_biomedical_link_to_bioportal:
    pattern:  /link_to_bioportal
    defaults: { _controller: AcmeBiomedicalBundle:SemanticDistance:indexRedirectToBioPortal }
    requirements: 
      _method: GET               