parameters:
#    acme_biomedical.example.class: Acme\BiomedicalBundle\Example

services:
#    acme_biomedical.example:
#        class: %acme_biomedical.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
